# pylint: disable=non-ascii-name

from typing import DefaultDict, Dict, List, TypedDict

from bs4 import BeautifulSoup as Soup

from custom_types import HTMLString, Kaki, Yomi, URL


# Jisho

class JishoDict(Dict):
    """Dictionary generated by the Jisho module upon fetching a word's definition etc"""


# Accents

class AccentDict(TypedDict):
    """Dictionary generated by modules that fetch the accent of words (ie OJAD, Suzuki, Wadoku)"""
    expected_output: Dict[Kaki, List[Yomi]]


class OjadExpectedSection(TypedDict):
    """Dictionary containing an HTML section extracted by the OJAD module
    and its contained information"""
    na_adj: bool
    writing_section: Soup
    writings: List[Kaki]
    reading_sections: List[Soup]
    readings: List[Yomi]


class OjadAccentDict(AccentDict):
    """Dictionary generated by the OJAD module"""
    htmls: List[HTMLString]
    url: URL
    expected_sections: List[OjadExpectedSection]
    full_accent_dict: DefaultDict[Kaki, List[Yomi]]


class SuzukiExpectedSection(TypedDict):
    """Dictionary containing an HTML section extracted by the Suzuki module
    and its contained information"""
    writing_section: Soup
    writing: Kaki
    reading_section: Soup
    accent_section: Soup
    reading: Yomi


class SuzukiAccentDict(AccentDict):
    """Dictionary generated by the Suzuki module"""
    html: HTMLString
    formdata: Dict[str, str]
    expected_sections: List[SuzukiExpectedSection]


class WadokuExpectedSection(TypedDict):
    """Dictionary containing an HTML section extracted by the Wadoku module
    and its contained information"""
    writing_section: Soup
    writings: List[Kaki]
    reading_sections: Soup
    readings: List[Yomi]


class WadokuAccentDict(AccentDict):
    """Dictionary generated by the Wadoku module"""
    html: HTMLString
    url: URL
    expected_sections: List[WadokuExpectedSection]
    full_accent_dict: DefaultDict[Kaki, List[Yomi]]


# Audio

class AudioDict(Dict):
    """Dictionary generated by modules that fetch audio files of words (ie Forvo, Wanikani)"""


# Expected final result

class ExpectedResultAccents(TypedDict):
    """File of the final result containing the fetched accented readings"""
    ojad: List[Yomi]
    suzuki: List[Yomi]
    wadoku: List[Yomi]

class ExpectedResultAudio(TypedDict):
    """Field of the final result containing URLs to audio files"""
    forvo: List[URL]
    wanikani: List[URL]

class ExpectedResult(TypedDict):
    """Expected output for the main get_info() function"""
    word: Kaki
    jisho: JishoDict
    accent: ExpectedResultAccents
    audio: ExpectedResultAudio


# Complete test dictionary type

class FullTestDict(TypedDict):
    """A dictionary containing all the information and expected results for any test"""
    id: str
    input: List[Kaki]
    jisho: JishoDict
    ojad: OjadAccentDict
    suzuki: SuzukiAccentDict
    wadoku: WadokuAccentDict
    forvo: AudioDict
    wanikani: AudioDict
    expected_result: List[ExpectedResult]
