from bs4 import BeautifulSoup as Soup
from bs4.element import PageElement as PageElement
from typing import DefaultDict, Dict, List, Tuple

NAME: str

def main(word_list: List[str]) -> Dict[str, List[str]]: ...
def get_url(word_list: List[str], page_number: int) -> str: ...
def get_rows(html_page: Soup) -> List[PageElement]: ...
def has_words(html_page: Soup) -> bool: ...
def get_html(word_list: List[str], page_number: int) -> Soup: ...
def get_htmls(word_list: List[str]) -> List[Soup]: ...
def get_sections(htmls: List[Soup]) -> List[Tuple[Soup, List[Soup]]]: ...
def extract_writings(writing_html: Soup) -> List[str]: ...
def extract_reading(reading_html: Soup, na_adj: bool) -> str: ...
def build_accent_dict(word_sections: List[Tuple[Soup, List[Soup]]]) -> DefaultDict[str, List[str]]: ...
