from bs4 import BeautifulSoup as Soup
from typing import Dict, List, Tuple

NAME: str

def main(word_list: List[str]) -> Dict[str, List[str]]: ...
def get_formdata(word_list: List[str]) -> Dict[str, str]: ...
def get_html(word_list: List[str]) -> Soup: ...
def get_sections(html: Soup) -> List[Tuple[Soup, Soup, Soup]]: ...
def extract_writing(writing_html: Soup) -> str: ...
def extract_characters(reading_html: Soup) -> str: ...
def extract_accent_pattern(accent_html: Soup) -> List[int]: ...
def contruct_reading(chars: str, accent_pattern: List[int]) -> str: ...
def extract_reading(reading_html: Soup, accent_html: Soup) -> str: ...
def build_accent_dict(word_sections: List[Tuple[Soup, Soup, Soup]]) -> Dict: ...
