from bs4 import BeautifulSoup as Soup
from typing import DefaultDict, Dict, List, Tuple

NAME: str

def main(word_list: List[str]) -> Dict[str, List[str]]: ...
def get_url(word_list: List[str]) -> str: ...
def get_html(word_list: List[str]) -> Soup: ...
def get_sections(html: Soup) -> List[Tuple[Soup, List[Soup]]]: ...
def extract_writings(writing_html: Soup) -> List[str]: ...
def extract_reading(reading_html: Soup) -> str: ...
def build_accent_dict(word_sections: List[Tuple[Soup, List[Soup]]]) -> DefaultDict: ...
