from typing import Iterator, Pattern

from bs4.element import Tag

class BeautifulSoup:
    text: str
    nextSibling: Tag | str
    def __init__(self, markup: str, parser: str) -> None: ...
    def __getitem__(self, index: str) -> list[str]: ...
    def __iter__(self) -> Iterator[BeautifulSoup]: ...
    def decompose(self) -> None: ...
    def find(
        self, name: str, class_: str | None = None, id: Pattern | None = None
    ) -> BeautifulSoup: ...
    def find_all(
        self, name: str, class_: str | None = None, id: Pattern | None = None
    ) -> list[BeautifulSoup]: ...
    def findChildren(
        self, name: str | None = None, recursive: bool | None = True
    ) -> list[BeautifulSoup]: ...
    def findChild(self, name: str | None = None) -> BeautifulSoup: ...
    def get(self, attr: str) -> str: ...
    def insert_after(self, text: str) -> None: ...
