from flask.wrappers import Request
from typing import Any

def get_words_from_request(request: Request): ...
def create_successful_response(payload: Any): ...
def create_failed_response(payload: Any): ...
def remove_punct(input_string: str) -> str: ...
def make_single_line(input_string: str) -> str: ...
