from testing.dict_typing import FullTestDict as FullTestDict
from typing import Any

def test_dict(request): ...

class FakeResponse:
    text: Any
    def __init__(self, text) -> None: ...

def test_main(monkeypatch, test_dict: FullTestDict): ...
def test_main_recursion(monkeypatch): ...
def test_empty_input() -> None: ...
def test_get_url(test_dict: FullTestDict): ...
def test_get_sections(test_dict: FullTestDict): ...
def test_extract_writings(test_dict: FullTestDict): ...
def test_extract_readings(test_dict: FullTestDict): ...
def test_build_accent_dict(test_dict: FullTestDict): ...
