from testing.dict_typing import FullTestDict as FullTestDict
from typing import Any

def test_dict(request): ...

class FakeResponse:
    text: Any
    def __init__(self, text) -> None: ...

def test_main(monkeypatch, test_dict: FullTestDict): ...
def test_empty_input() -> None: ...
def test_get_url(test_dict: FullTestDict, page_number: int): ...
def test_has_words_true(test_dict: FullTestDict): ...
def test_has_words_false() -> None: ...
def test_get_htmls(monkeypatch, test_dict: FullTestDict): ...
def test_get_sections(test_dict: FullTestDict): ...
def test_extract_writings(test_dict: FullTestDict): ...
def test_extract_reading(test_dict: FullTestDict): ...
def test_build_accent_dict(test_dict: FullTestDict): ...
