from testing.dict_typing import FullTestDict as FullTestDict
from typing import Any

def test_dict(request): ...

MODULES: Any

def no_requests(monkeypatch) -> None: ...
def test_get_info(monkeypatch, test_dict: FullTestDict): ...
def test_generate_results_dict(monkeypatch, test_dict): ...
def test_generate_response(test_dict: FullTestDict): ...
