on: [workflow_call]

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd react_interface
    - name: Test using Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn test
