on: [workflow_call]

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test using Node.js
      working-directory: ./react-interface
      uses: actions/setup-node@v1
      with:
        node-version: '14'
      run: |
        yarn install
        yarn test
