on: [workflow_call]

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      working-directory: ./react-interface
      run: yarn install
    - name: Test with jest
      working-director: ./react-interface
      run: yarn test
