on: [workflow_call]

defaults:
  run:
    working-directory: ./client

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn install
    - name: Test with jest
      run: yarn test
