# This workflow will install Python dependencies, run tests for function, linting and typing with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push Changes

on:
  push:
    branches:
      '*'

jobs:
  tests:
    name: Tests
    uses: benleong0/japanese_vocab_fetcher/.github/workflows/tests.yml@eefb52d6b7d2f0e24e71c34c1a32e06c8733c822
