on: [workflow_call]

defaults:
  run:
    working-directory: api

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get python version
      run: |
        python_version=$(cat deployment/.python-version)
        echo "PYTHON_VERSION=${python_version}" >> $GITHUB_ENV
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        python -m poetry install
    - name: Check formatting with pylint
      run: |
        poetry run ruff check
        poetry run ruff format --check


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get python version
      run: |
        python_version=$(cat deployment/.python-version)
        echo "PYTHON_VERSION=${python_version}" >> $GITHUB_ENV
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        python -m poetry install
    - name: Test with pytest
      run: |
        echo FORVO_API_KEY = 00000000000000000000000000000000 >> .env
        echo WANIKANI_API_KEY = 00000000-0000-0000-0000-000000000000 >> .env
        poetry run pytest


  type-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get python version
      run: |
        python_version=$(cat deployment/.python-version)
        echo "PYTHON_VERSION=${python_version}" >> $GITHUB_ENV
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        python -m poetry install
    - name: Test typing with mypy
      run: |
        poetry run pyright
