# This workflow will install Python dependencies, run tests for function, linting and typing with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build to Docker

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          VERSION="$GITHUB_REF"
