# This workflow will install Python dependencies, run tests for function, linting and typing with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on:
  push:
    branches:
      '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/tests.yml@Dockerise
